language: ruby
before_install:
  - travis_retry gem install bundler
rvm:
  - "2.0.0"
gemfile: Gemfile
script: 
  - bundle
  - bundle install
  - cd test; 
  - ruby test_echo.rb
notifications:
  recipients:
    - scott.sproule@estormtech.com
  email:
    on_success: change
    on_failure: always
addons:
  code_climate:
    repo_token: cef4c4a2ae0686cd38f4ea7b414344900a687bf7375f3cc320cc3542813f068e
